package io.github.cyning.greendao;

import io.github.cyning.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.io.Serializable;
import com.google.gson.annotations.SerializedName;
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table "HOT_ARTICLE".
 */
public class HotArticle implements Serializable {

     @SerializedName("groupName")
    private String groupName;
    private String title;
     @SerializedName("descrip")
    private String abstractX;
     @SerializedName("seriNo")
    private String serNo;
    private String category;
     @SerializedName("url")
    private String link;
    private String imgUrl;
     @SerializedName("publishTime")
    private String updateTime;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient HotArticleDao myDao;


    // KEEP FIELDS - put your custom fields here
    private List<String> images;

    private String flag;
    // KEEP FIELDS END

    public HotArticle() {
    }

    public HotArticle(String link) {
        this.link = link;
    }

    public HotArticle(String groupName, String title, String abstractX, String serNo, String category, String link, String imgUrl, String updateTime) {
        this.groupName = groupName;
        this.title = title;
        this.abstractX = abstractX;
        this.serNo = serNo;
        this.category = category;
        this.link = link;
        this.imgUrl = imgUrl;
        this.updateTime = updateTime;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getHotArticleDao() : null;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAbstractX() {
        return abstractX;
    }

    public void setAbstractX(String abstractX) {
        this.abstractX = abstractX;
    }

    public String getSerNo() {
        return serNo;
    }

    public void setSerNo(String serNo) {
        this.serNo = serNo;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
